### ISSUE TITLE
响应式导航栏

### ISSUE THREAD

**Issue by KYLN24** [DanXi-Dev/danxi-website-old#1]
网页顶部导航栏在窄屏设备上的表现不佳，可参考 apple.com 的做法

**Comment by KYLN24** [comment]
即将把该项目使用某前端框架重构

**Comment by w568w** [comment]
Since we have refactored it, has it resolved now?

**Comment by Gaia-pygmalion** [comment]
> 

额……还没有 那我今天改一下

**Comment by Gaia-pygmalion** [comment]
> Since we have refactored it, has it resolved now?

额……还没有 那我今天改一下
现在应该好了
