### ISSUE TITLE
更新 Android 下载链接和其他信息

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/danxi-website-old#5]
官网上的这些链接已经失效了：

1. Android 下载链接：蒲公英已关停应用
2. FastGit 镜像：已关停
3. 友情链接：https://kavinzhao.github.io/ https://blog.salve.cf/ 

---

官网上的这些信息已经失效了：

1. 「旦夕」团队结构：https://danxi.fduhole.com/about 
2. FDUHole 管理团队负责人邮箱：https://danxi.fduhole.com/about 
4. 更新日志：https://danxi.fduhole.com/version （建议直接导航到 https://github.com/DanXi-Dev/DanXi/releases ）

**Comment by KYLN24** [comment]
团队结构已移除，社区运营部负责人邮箱已更改。其他部分将在新官网中完善。
